### ISSUE TITLE
The name ncolide was better

### ISSUE THREAD

**Issue by EdorianDark** [dimforge/parry#1]
Maybe this could be a huge breaking change to ncollide?

**Comment by sebcrozet** [comment]
Hi! So right now I’m not sure yet about what this crate will end up being. As you suggested, there are two options:
- Make this a breaking change for ncollide.
- Make this a new crate that would be the successor of ncollide. The current name `cdl` (i.e. Collision Detection Library) is by no means definitive. 

Right now I am working on a separate crate because it is just easier for me to work that way.
The main reason why I am thinking of making a new crate instead of just a new version of ncollide is that, as you said, this is a huge breaking change (including the removal of some features like the `CollisionWorld` and generics wrt. the scalar type).

So this is all open to discussion if you happen to have some specific ideas on why this should just be a breaking change for ncollide or not.

No matter the choice being made, these changes (or new crate) will be released at the end of January 2021. So we have till then to decide.

**Comment by EdorianDark** [comment]
I think it is important for a project to have a pronounceable and recognizable name.
And in my subjective opinion I think that ```ncollide``` is better than ```cdl```.

**Comment by jbowtie** [comment]
I agree that `cdl` is a terrible name, largely because it used as a three-letter acronym in many, many fields and that will be terrible for people attempting to locate the right library.

I see no reason not to continue using `ncollide` with a major version bump. Alternatively, maybe consider a fencing term since this is meant to work with Rapier -- something like `touche` (the fencing term for a contact) seems both an appropriate metaphor and easier to remember.

**Comment by sebcrozet** [comment]
@jbowtie Thank you for your input. I am certain now that this will be a new crate instead of a major version bump of `ncollide`. The main reason is that making a major version bump of `ncollide` would imply that `nphysics` would become completely unmaintained (because `nphysics` uses generics so it would not be able to upgrade to that new version of `ncollide`. And if it cannot upgrade to the latest `ncollide` it won't be able to upgrade to the latest `nalgebra` to avoid incompatibility with the older version of `ncollide`). And because there are some features `nphysics` has that `rapier` does not have yet (like deformable bodies, multibodies, and the ability to use fixed-point numbers), I am not ready to completely drop maintainance `nphysics` just yet.

Though I agree the three-letters names `cdl` isn't very good. The name `touche` is an interesting suggestion but I am affraid people could be confused with `touch` (which already has many names in CS, like touch events, touch the command-line, etc.) Right now I settled with `parry`, which is a word that appears frequently in games and also seems appropriate.

**Comment by sebcrozet** [comment]
The crates have been released with the names `parry2d`, `parry3d`, `parry2d-f64` and `parry3d-f64`!
